[package]
name = "sart"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.95"

[dependencies]
pastey = "^0.2"
serde = { version = "^1", features = ["derive"] }

saffi = { path = "./saffi/ffi" }

# LibFFI System
libffi-sys = "^4"

[features]
default = []
ffi_system = ["libffi-sys/system"]
